### ISSUE TITLE
Print "updated" dates in the cli output

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/missed-issues#9]
As a follow up to #7, it would be nice in the updated times were printed as part of the markdown from the CLI tool. I think we can skip created as the issue number is printed which gives you a sense of how old the issue is.

Right now the output of the cli looks like this:

```
## check-file-dependencies

- [ ] [#1 - first issue](https://github.com/mapbox/check-file-dependencies/issues/new)
- [ ] [#2 - another issue](https://github.com/mapbox/check-file-dependencies/issues/new)
- [ ] [#3 - yet another issue](https://github.com/mapbox/check-file-dependencies/issues/new)

## missed-issues

- [ ] [#42 - Document the node module interface](https://github.com/mapbox/missed-issues/issues/new)
```

After this issue the output should look like:

```
## check-file-dependencies

**2017-11-18**

- [ ] [#1 - first issue](https://github.com/mapbox/check-file-dependencies/issues/new)
- [ ] [#2 - another issue](https://github.com/mapbox/check-file-dependencies/issues/new)

**2017-11-19**

- [ ] [#3 - yet another issue](https://github.com/mapbox/check-file-dependencies/issues/new)

## missed-issues

**2017-11-17**

- [ ] [#42 - Document the node module interface](https://github.com/mapbox/missed-issues/issues/new)
```

**Comment by mohit2agrawal** [comment]
Hi!! Can I take a look into this if nobody else is on it? Thanks...

**Comment by mcwhittemore** [comment]
@mohit2agrawal Please do!

**Comment by mohit2agrawal** [comment]
@mcwhittemore Created PR #10. Please check.

**Comment by mcwhittemore** [comment]
Closed via #10
